library(ggplot2)
library(ggmap)
library(gridExtra)
library(scales)
library(plyr)
library(reshape)
library(spdep)
library(gstat)
library(bigmemory)

setwd("~/Professional Files/Mines/SmartGeo/Queens/")
load("Data/Cleaned_Data.RData")
groundBM = attach.big.matrix("Data/groundBM.desc")
cnames = read.csv("Data/groundBM_cnames.csv", stringsAsFactors=F)[,1]
source("~/Professional Files/Mines/Research/Wind QC/Code/SNHT functions for Mandy.R")
